server {
    listen 80;
    server_name _;

    location /api/ {
        proxy_pass http://iqa-api:8000/;
    }

    location /iqa/ {
        proxy_pass http://iqa-streamlit:8501/;
    }

    location /mlflow/ {
        proxy_pass http://mlflow:5000/;
    }

    location /minio/ {
        proxy_pass http://minio:9001/;
    }

    location /grafana/ {
        proxy_pass http://grafana:3000/;
    }

    location /airflow/ {
        proxy_pass http://airflow-webserver:8080/;
    }
}
