server {
    listen 80;
    server_name _;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/ {
        set $iqa_api iqa-api:8000;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://$iqa_api;
    }

    location /iqa/ {
        set $iqa_streamlit iqa-streamlit:8501;
        rewrite ^/iqa/(.*)$ /$1 break;
        proxy_pass http://$iqa_streamlit;
    }

    location /mlflow/ {
        set $mlflow mlflow:5000;
        rewrite ^/mlflow/(.*)$ /$1 break;
        proxy_pass http://$mlflow;
    }

    location /minio/ {
        set $minio minio:9001;
        rewrite ^/minio/(.*)$ /$1 break;
        proxy_pass http://$minio;
    }

    location /grafana/ {
        set $grafana grafana:3000;
        rewrite ^/grafana/(.*)$ /$1 break;
        proxy_pass http://$grafana;
    }

    location /airflow/ {
        set $airflow airflow-webserver:8080;
        rewrite ^/airflow/(.*)$ /$1 break;
        proxy_pass http://$airflow;
    }
}
