services:
  iqa-inference:
    build:
      context: ..
      target: ml
      args:
        IQA_TORCH_EXTRA: cu128
    command: iqa-inference
    gpus: all

  iqa-trainer:
    build:
      context: ..
      target: ml
      args:
        IQA_TORCH_EXTRA: cu128
    command: iqa-run-lifecycle
    gpus: all
